---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sshd-jumpserver-rc
spec:
  replicas: 1
  selector:
    app: sshd-jumpserver
  template:
    metadata:
      labels:
        app: sshd-jumpserver
    spec:
      containers:
      - name: sshd-jumpserver
        image: kubernetesio/sshd-jumpserver
        ports:
          - containerPort: 22
        env:
          - name: PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: sshkey
                key: authorizedkeys
