---
apiVersion: v1
kind: Service
metadata:
  name: sshd-jumpserver-svc
  labels:
    name: sshd-jumpserver-svc
spec:
  ports:
    - name: ssh
      port: 22
  type: "LoadBalancer"
  selector:
    app: sshd-jumpserver
